driver:
  name: docker

provisioner:
  name: chef_zero
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10

platforms:
  - name: centos-7.1
suites:
  - name: openjdk-6
    includes:
      - centos-7.1
    run_list:
      - recipe[java::default]
    attributes:
  