AllCops:
  Exclude:
    - 'cookbooks/*/Berksfile'
    - 'cookbooks/*/Thorfile'
    - 'cookbooks/*/Vagrantfile'
    - 'Gemfile'
    - 'cookbooks/*/metadata.rb'
    - 'Rakefile'
    - 'cookbooks/*/spec/*_spec.rb'
    - 'environments/*'

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
SpaceBeforeFirstArg:
  Enabled: false
StringLiterals:
  Enabled: false
AsciiComments:
  Enabled: false
Style/FileName:
  Enabled: false
