---
driver:
  name: docker
  #socket: tcp://52.33.252.193:2376

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[starter::default]
    attributes:
