AllCops:
  Exclude:
    - 'Berksfile'
    - 'Thorfile'
    - 'Vagrantfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'Rakefile'
    - 'spec/*_spec.rb'

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

AsciiComments:
  Enabled: false

MethodLength:
  Max: 18

Style/FileName:
  Enabled: false
