---
driver:
  name: docker
  socket: tcp://52.33.252.193:2376

provisioner:
  name: chef-zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[repotest1::default]
    attributes:
